### PR TITLE
Removed inclusions of ai/aliases/stable_singleplayer.cfg

### PR DESCRIPTION
**Pull request by Vultraz**
According to mattsc, this inclusion is redundant as there are no other AI engines
loaded besides the default one

### CODE REVIEW

**Comment by shikadilord** [comment]
Then shouldn't you leave them intact wherever a Lua AI engine is used?

**Comment by Vultraz** [comment]
Where is it used? I thought that meant the Micro AIs.

**Comment by shikadilord** [comment]
The ``AI_BOSS_TARGETING_ENGINE`` macro.

**Comment by Vultraz** [comment]
Done. I also fixed the macro always targeting side 2.

**Comment by shikadilord** [comment]
Commit 9d843a8283b93203d24a935e7d5871362ada4515 needs to be squashed into its parent.

**Comment by Vultraz** [comment]
Done. I also preserved the inclusions that are deleted in PR #8 94b137ee053772163e25583a581cffd145c49bdb, so these two can be merged cleanly.

**Comment by shikadilord** [comment]
As I mentioned on IRC, removing these has a great potential for bugs later on if I decide to drop a Lua engine on any other existing side definition that didn't use one before.

Also, the bug with ``[modify_ai] side=`` turned out to not actually be such; see commit 09fd6bbcff7ed7a9298993b15077737b0ed243bb.

Closing this.

**Pull request closed without merging**
